---
storage:
  type: sqlite
  path: /data/data.db

endpoints:
  - name: Jellyfin
    group: Media
    url: "https://jellyfin.elvishlegion.com"
    interval: 60s
    conditions:
      - "[STATUS] == 200"

  - name: Minecraft Server
    group: Game Infrastructure
    url: "icmp://minecraft.tail5859ca.ts.net"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"

  - name: Media VPS
    group: Infrastructure
    url: "icmp://media-vps.tail5859ca.ts.net"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"

  - name: MC Stats
    group: Game Infrastructure
    url: "https://mcstats.elvishlegion.com/healthz"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].ok == true"
      - "has([BODY].players) == true"
      - "[RESPONSE_TIME] < 2000"
      - "[CERTIFICATE_EXPIRATION] > 168h"
  - name: Minecraft Game
    group: Game Infrastructure
    url: "tcp://minecraft.tail5859ca.ts.net:25565"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
